file_types:
  inode/directory: exa -T '{}'
  inode/*: file -I {}
  application/zip,.zip: zipinfo '{}'
  application/vnd.sqlite3,.sqlite: sqlite3 '{}' .tables | tr -s " " "\n" | xargs -I+ sqlite3 -cmd "select char(10) || '+:'" -cmd ".mode columns" -cmd "pragma table_info('+')" '{}'
  application/gzip,.gz: tar -tf '{}'
  default: head -100
